# This is a basic workflow to help you get started with Actions
name: DownLoad CEF CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab, 手动触发
  workflow_dispatch:
    inputs:
      cef_version:
        description: '获取cef 二进制文件版本'
        required: true
        default: '108.4.13+ga98cd4c+chromium-108.0.5359.125'
      platform:
        description: '平台'
        required: true
        default: 'windows32'

env:
  GLOBAL_CEF_URL:  https://cef-builds.spotifycdn.com
  BASE_FILE_STUFFIX: tar.bz2.tar
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # create dir
      - name: create dir
        run: |
          export BASE_DOWNLOAD_PATH=$(pwd)/source/cef_binary_${{ github.event.inputs.cef_version }}_${{ github.event.inputs.platform }}
          mkdir -p ${BASE_DOWNLOAD_PATH}
          echo "create success => ${BASE_DOWNLOAD_PATH}"

      # Runs a single command using the runners shell
      - name: Download cef source code
        run: |
          BASE_FILE_NAME=cef_binary_${{ github.event.inputs.cef_version }}_${{ github.event.inputs.platform }}.${{ env.BASE_FILE_STUFFIX }}
          if [ -f "${BASE_DOWNLOAD_PATH}/${BASE_FILE_NAME}" ]; then
            echo "${BASE_FILE_NAME} 已存在，跳过下载"
          else
            curl -L -o "${BASE_DOWNLOAD_PATH}/${BASE_FILE_NAME}" "${{ env.GLOBAL_CEF_URL }}/${BASE_FILE_NAME}"
            echo "resource=> ${{ env.GLOBAL_CEF_URL }}/${BASE_FILE_NAME} downloaded"
          fi
          echo "resource path:  ${BASE_DOWNLOAD_PATH}/${BASE_FILE_NAME}"

      - name: Download debug cef symbols file
        run: |
          BASE_DEBUG_SYMBOLS_FILE_NAME=cef_binary_${{ github.event.inputs.cef_version }}_${{ github.event.inputs.platform }}_debug_symbols.${{ env.BASE_FILE_STUFFIX }}
          if [ -f "${BASE_DOWNLOAD_PATH}/${BASE_DEBUG_SYMBOLS_FILE_NAME}" ]; then
            echo "${BASE_DEBUG_SYMBOLS_FILE_NAME} 已存在，跳过下载"
          else
            curl -L -o "${BASE_DOWNLOAD_PATH}/${BASE_DEBUG_SYMBOLS_FILE_NAME}" "${{ env.GLOBAL_CEF_URL }}/${BASE_DEBUG_SYMBOLS_FILE_NAME}"
            echo "resource=> ${{ env.GLOBAL_CEF_URL }}/${BASE_DEBUG_SYMBOLS_FILE_NAME} downloaded"
          fi
          echo "resource path:   ${BASE_DOWNLOAD_PATH}/${BASE_DEBUG_SYMBOLS_FILE_NAME}"

      - name: Download release cef symbols file
        run: |
          BASE_RELEASE_SYMBOLS_FILE_NAME=cef_binary_${{ github.event.inputs.cef_version }}_${{ github.event.inputs.platform }}_release_symbols.${{ env.BASE_FILE_STUFFIX }}
          if [ -f "${BASE_DOWNLOAD_PATH}/${BASE_RELEASE_SYMBOLS_FILE_NAME}" ]; then
            echo "${BASE_RELEASE_SYMBOLS_FILE_NAME} 已存在，跳过下载"
          else
            curl -L -o "${BASE_DOWNLOAD_PATH}/${BASE_RELEASE_SYMBOLS_FILE_NAME}" "${{ env.GLOBAL_CEF_URL }}/${BASE_RELEASE_SYMBOLS_FILE_NAME}"
            echo "resource=> ${{ env.GLOBAL_CEF_URL }}/${BASE_RELEASE_SYMBOLS_FILE_NAME} downloaded"
          fi
          ls
          echo "resource path:   ${BASE_DOWNLOAD_PATH}/${BASE_RELEASE_SYMBOLS_FILE_NAME}"

      - name: Check if tag exists
        id: check_tag
        uses: actions/github-script@v7
        with:
          script: |
            const tag = '${{ github.event.inputs.cef_version }}_${{ github.event.inputs.platform }}';
            const { data: tags } = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });
            const exists = tags.some(t => t.name === tag);
            core.setOutput('tag_exists', exists);
            ls ${BASE_DOWNLOAD_PATH}
      # 创建release
      - name: Create Release
        if: steps.check_tag.outputs.tag_exists != 'true'
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.cef_version }}_${{ github.event.inputs.platform }}
          name: CEF binary ${{ github.event.inputs.cef_version }}_${{ github.event.inputs.platform }}
          body: |
            自动下载的 CEF 二进制包和符号文件
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 上传文件到release（仅当tag不存在时）
      - name: Upload assets to release
        if: steps.check_tag.outputs.tag_exists != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.cef_version }}_${{ github.event.inputs.platform }}
          files: ${BASE_DOWNLOAD_PATH}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
